import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import homeimg from "../public/iso.png";
import unitylogo from "../public/unitylogo.png";
import csharpogo from "../public/csharpogo.png";
import react from "../public/reactlogo.png";
import { useState } from "react";
import oneproject from "../public/oneproject.png";
import twoproject from "../public/twoproject.png";
import threeproject from "../public/threeproject.png";
import fakeshop from "../public/fakeshop.png";
import cryptotracker from "../public/cryptotracker.png";
import randomphoto from "../public/randomphoto.png";




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>İsmail Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-5xl font-rightheous dark:text-gray-50">
              epsilon
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer dark:text-gray-50"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-red-800 to-red-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-orange-800 font-medium md:text-6xl dark:text-red-600">
              İsmail Çiftçi
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-100">
              Game Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-900  text- md:text-xl max-w-lg mx-auto dark:text-gray-400">
              Hello there! I am İsmail Çiftçi game developer.{" "}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-red-600">
            <a href="https://www.linkedin.com/in/ismail-%C3%A7ift%C3%A7i-86562918a/">
              {" "}
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/ismlciftci">
              {" "}
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/ismlciftci/">
              <AiFillInstagram />
            </a>
          </div>
          <p className="text-center dark:text-white dark:border-red-300 border-4 border-red-200 rounded-lg text-2xl">
            ismlciftci7@gmail.com
          </p>
          <div className="relative mx-auto bg-gradient-to-b from-red-500 rounded-full w-96  h-96 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={homeimg} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl py-5 text-center  text-gray-700 dark:text-gray-100">
              İsmail Çiftçi
            </h3>
            <p className="text-md py-2 text-center leading-8 text-gray-900 dark:text-gray-400">
              I graduated from Zonguldak Bulent Ecevit University, Computer
              Engineering. I was very interested in computers since childhood
              and this continued and developed with software in the following
              period. I have been in web development processes as an intern at
              Quantum Cyber Security and Zonguldak Bülent Ecevit University.
              Because of my interest in the game, I decided to continue my
              career in this direction and now I am working on game development.
            </p>
          </div>
          <div className="lg:flex gap-10 justify-center">
            <div className=" text-center shadow-lg p-10 dark:shadow-gray-600 rounded-xl my-10">
              <Image src={unitylogo} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100">
                Game Developer
              </h3>
            </div>

            <div>
              <div className=" text-center shadow-lg p-10 dark:shadow-gray-600 rounded-xl my-10">
                <Image src={csharpogo} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100">
                  Software
                </h3>
              </div>
            </div>
            <div>
              <div className=" text-center shadow-lg p-10 dark:shadow-gray-600 rounded-xl my-10">
                <Image src={react} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100">
                  Education
                </h3>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1">
              <Image
                src={oneproject}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <a
                className="flex justify-center text-xl hover:text-red-700 border-2 border-slate-500 dark:hover:text-red-500 dark:text-white"
                href="https://github.com/ismlciftci/Fps-Game-with-Unity"
              >
                FPS Game
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={twoproject}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <a
                className="flex justify-center text-xl hover:text-red-700 border-2 border-slate-500 dark:hover:text-red-500 dark:text-white"
                href="https://github.com/ismlciftci/Space-wars"
              >
                Space-Wars
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={threeproject}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <a
                className="flex justify-center text-xl hover:text-red-700 border-2 border-slate-500 dark:hover:text-red-500 dark:text-white"
                href="https://github.com/ismlciftci/Survivor-Game"
              >
                Survivor Game
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={fakeshop}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <a
                className="flex justify-center text-xl hover:text-red-700 border-2 border-slate-500 dark:hover:text-red-500 dark:text-white"
                href="https://github.com/ismlciftci/Fake-Shop"
              >
                Fake Shop
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={cryptotracker}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <a
                className="flex justify-center text-xl hover:text-red-700 border-2 border-slate-500 dark:hover:text-red-500 dark:text-white"
                href="https://github.com/ismlciftci/CryptoTracker"
              >
                Crypto Tracker
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={randomphoto}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <a
                className="flex justify-center text-xl hover:text-red-700 border-2 border-slate-500 dark:hover:text-red-500 dark:text-white"
                href="https://github.com/ismlciftci/website-that-brings-random-photos"
              >
                Random Photo
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
